### ISSUE TITLE
После апгрейда джанги сломались переводы

### ISSUE THREAD

**Issue by f213** [f213/education-backend#136]
![2021-01-13 17 57 41](https://user-images.githubusercontent.com/1592663/104468764-df1d6d80-55c8-11eb-8980-e042d656704b.jpg)

**Comment by AlexandrST** [comment]
Так, а коммит будет по этому багу ? Почему такое произошло ?

**Comment by gimntut** [comment]
1. В [OrdersConfig](https://github.com/f213/education-backend/blob/master/src/orders/apps.py) не указан verbose_name. Достаточно его указать и баг уйдёт
2. В INSTALLED_APPS вместо 'order' нужно писать 'orders.apps.OrdersConfig', т.е. то, что указывают в [default_app_config](https://github.com/f213/education-backend/blob/master/src/orders/__init__.py)
3. После выполнения пункта 2, default_app_config можно удалить из __init__.py

Все подробности здесь: https://docs.djangoproject.com/en/3.1/ref/applications/

**Comment by f213** [comment]
Кажется всё гораздо страннее — на моей машине при запуске через `./manage.py runserver` всё работает ок, а вот на проде в докере — «порядок».

**Comment by gimntut** [comment]
Т.е. получается, что язык локализации подхватывается, а файл с переводом - нет.
Значит на проде файл с переводами не скомпилировался. Других причин не вижу.
Проверь наличие mo-файла в докере.
В любом, случае verbose_name для AppConfig лишним не будет.

**Comment by f213** [comment]
Проблема была в процессе сборки, пофиксил.
