### ISSUE TITLE
Удовлетворить любопытство [pls :)]

### ISSUE THREAD

**Issue by Alex-Blade** [f213/education-backend#237]
> Do not use signals for business logic. Signals are good only for notification purposes.
(C) README.md

Не совсем issue, а скорее вопрос - что не так с Signals? Или речь идёт о какой-то специфичной  "business logic"?

**Comment by f213** [comment]
Сигналы размазывают бизнес-логику по приложению. В этом проекте мы практикуем сервисный подход, когда один сервисный объект отвечает за один кусок бизнес-истории. К примеру, благодаря сервису [UserCreator](https://github.com/f213/education-backend/blob/master/src/users/creator.py), создавая пользователя в любом месте системы, я могу быть уверен, что он будет подписан на мейлчимп, причём подписан в правильном состоянии — когда у него уже есть имя и фамилия.

Подробнее о сигналах, как об антипаттернах, можно почитать здесь https://lincolnloop.com/blog/django-anti-patterns-signals/
