### ISSUE TITLE
В ответах на домашку пропадают переносы на новую строку 

### ISSUE THREAD

**Issue by skatromb** [f213/education-backend#267]
Когда постишь ответы на домашку, для того, чтобы получить новый абзац, нужно сделать два переноса на новую строку, как в православном маркдауне. Это неочевидно для нормальных людей. 
В итоге текст, казавшийся разбитым на абзацы оказывается слит воедино. Пример в файлах во вложении.

Кажется, было бы круто врубить предпросмотр, как ты показывал на демке, или не схлопывать переносы на новую строку.

**Comment by f213** [comment]
@skatromb пожалуйста, никогда не пости сюда личные домашние задания учеников. Это — открытый проект, он и поисковиками индексируется. 

У меня, к сожалению, не хватает прав удалить эту issue. Важно: именно закрыть, а не удалить. Если не получится — придётся писать в сапорт.

**Comment by skatromb** [comment]
Черт, я совсем про это не подумал, извини. Забыл, что это открытый проект. Стыд.
Запомню на будущее.

——
Ivan Livadnyi

**Comment by f213** [comment]
@skatromb а что с удалением? У тебя есть кнопка «удалить»?

**Comment by f213** [comment]
Ой, я и сам нашёл. Всё. убиваю.
