### ISSUE TITLE
На фронте дублируются домашки

### ISSUE THREAD

**Issue by f213** [f213/education-backend#278]
К примеру `d3d08e11-cc4e-4785-a13b-d72189bce161` показывается у её автора три раза.

**Comment by skatromb** [comment]
Сегодня была ещё пара отзывов на дублирование в телеграме. Если потребуется, раскопаю ссылки.

**Comment by f213** [comment]
Нет смысла, мне понятно, как воспроизвести.

Спасибо!

**Comment by f213** [comment]
Фикс в 9a10071e42f85e0573ddb08d78690644099937a9
